version: '3.7'

services:
  mariadb:
    image: mariadb@sha256:ec97b993b11423a5b60448c85e01e3f696aaf6dfbf6f83c12d03bb02563f134e
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - tfpwa
  wordpress:
    build:
      context: .docker/wordpress
      dockerfile: Dockerfile
      args:
        VERSION: ${WP_VERSION:-php8.0}
    depends_on:
      - mariadb
    ports:
      - 8443:443
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    volumes: &ref_0
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/two-factor-provider-webauthn
    networks:
      - tfpwa
  cli:
    image: wordpress:cli-php8.0@sha256:fcf8335c4f1e51c5efcf9af694f325f69c931cad0f993d4077c4f5f9249fdd46
    volumes: *ref_0
    user: '33:33'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    networks:
      - tfpwa

networks:
  tfpwa:
volumes:
  mysql:
  wordpress:
