version: '3.7'

services:
  mariadb:
    image: mariadb@sha256:f592a5a56c3eda797f3cc903baac54226e7b2cea889fa3208b5c0df3fa9f87f2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - tfpwa
  wordpress:
    build:
      context: .docker/wordpress
      dockerfile: Dockerfile
      args:
        VERSION: ${WP_VERSION:-php7.4}
    depends_on:
      - mariadb
    ports:
      - 8443:443
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    volumes: &ref_0
      - 'wordpress:/var/www/html'
      - .:/var/www/html/wp-content/plugins/two-factor-provider-webauthn
    networks:
      - tfpwa
  cli:
    image: 'wordpress:cli-php7.4@sha256:e0ef8000da29a406afc70e9343aca4c273865868f1f405cf9d0220ac4c1a6480'
    volumes: *ref_0
    user: '33:33'
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    networks:
      - tfpwa

networks:
  tfpwa:
volumes:
  mysql:
  wordpress:
