name: E2E Testing

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Set up Node.js environment
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up PHP
        uses: shivammathur/setup-php@d37cc3048580de06099c81ded417530716a0d7ab # tag=2.18.0

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # renovate: tag=2.1.0

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run PlaywrightE2E tests
        run: npm run test:e2e

      - name: Upload test results
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3
        if: failure()
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 3
