name: E2E Testing

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  e2e:
    name: "Run E2E tests (use wordpress:${{ matrix.wordpress }} image)"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wordpress:
          - php7.4
          - php8.0
          - php8.1
          - beta-php7.4
          - beta-php8.0
          - beta-php8.1
    steps:
      - name: Checkout source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up Node.js environment
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3.3.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up PHP
        uses: shivammathur/setup-php@3312ea6101295aeda1e702b5d3b641e9717de6d6 # tag=2.20.1

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # renovate: tag=2.1.0

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run Playwright E2E tests
        run: npm run test:e2e
        env:
          WP_VERSION: ${{ matrix.wordpress }}

      - name: Upload test results
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        if: failure()
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 3
