name: Code Standards Compliance Checks

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: none

jobs:
  php:
    name: Lint PHP files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up PHP
        uses: shivammathur/setup-php@fc14643b0a99ee9db10a3c025a33d76544fa3761 # 2.30.5
        with:
          coverage: none
        env:
          fail-fast: 'true'

      - name: Install dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # 3.0.0

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/checkstyle-problem-matcher.json"

      - name: Run style check
        run: composer phpcs -- --report=checkstyle

  js:
    name: Lint JS files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node.js environment
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run style check
        run: npm run lint -- -f gha
