name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Generate self-contained package
        run: |
          git archive --format=tar --prefix=two-factor-provider-webauthn/ HEAD | (cd /var/tmp/ && tar xf -)
          cp composer.lock /var/tmp/two-factor-provider-webauthn/
          (cd /var/tmp/two-factor-provider-webauthn && composer install --no-dev --no-interaction && composer remove --update-no-dev --no-interaction composer/installers && rm -f composer.lock)
          (cd /var/tmp && zip -r -9 two-factor-provider-webauthn.zip two-factor-provider-webauthn)

      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v0.1.14
        with:
          generate_release_notes: true
          files: |
            /var/tmp/two-factor-provider-webauthn.zip

  deploy:
    name: Deploy to wordpress.org
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: deploy
    steps:
      - name: Check out
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Install dependencies to bundle
        run: |
          composer install --no-dev --no-interaction
          composer remove --update-no-dev --no-interaction composer/installers
          rm -f composer.lock composer.json

      - name: Deploy to wordpress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: two-factor-provider-webauthn
